<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" source-language="en" target-language="es" original="../ExtensionResources.resx">
    <body>
      <trans-unit id="FailedToCreateRetryDirectoryBecauseOfCollision">
        <source>Failed to create retries directory due to collisions in '{0}' despite re-trying.</source>
        <target state="translated">No se pudo crear el directorio de reintentos debido a colisiones en '{0}' a pesar de volver a intentarlo.</target>
        <note>'{0}' is the directory where collisions happen</note>
      </trans-unit>
      <trans-unit id="FailureThresholdPolicy">
        <source>Failure threshold policy is enabled, failed tests will not be restarted.</source>
        <target state="translated">La directiva de umbral de errores está habilitada; no se reiniciarán las pruebas con errores.</target>
        <note />
      </trans-unit>
      <trans-unit id="FailureThresholdPolicyMaxCount">
        <source>Maximum failed tests threshold is {0} and {1} tests failed</source>
        <target state="translated">El umbral máximo de pruebas con errores es {0} y {1} pruebas erróneas</target>
        <note />
      </trans-unit>
      <trans-unit id="FailureThresholdPolicyMaxPercentage">
        <source>Percentage failed threshold is {0}% and {1}% tests failed ({2}/{3})</source>
        <target state="translated">El umbral de porcentaje de errores es {0}% y {1}% de pruebas no superadas ({2}/{3})</target>
        <note />
      </trans-unit>
      <trans-unit id="MoveFiles">
        <source>
=====================
Moving last attempt asset files to the default result directory
=====================
</source>
        <target state="translated">
=====================
Moviendo los archivos de recursos del último intento al directorio de resultados predeterminado
=====================
</target>
        <note />
      </trans-unit>
      <trans-unit id="MovingFileToLocation">
        <source>Moving file '{0}' to '{1}'</source>
        <target state="translated">Moviendo el archivo '{0}' a '{1}'</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsCannotStartProcessErrorMessage">
        <source>Failed to start process '{0}'</source>
        <target state="translated">No se pudo iniciar el proceso '{0}'</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsExtensionDescription">
        <source>Retry failed tests feature allows to restart test execution upon failure.</source>
        <target state="translated">La característica Reintentar pruebas con errores permite reiniciar la ejecución de pruebas en caso de error.</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsExtensionDisplayName">
        <source>Retry failed tests</source>
        <target state="translated">Reintentar pruebas con errores</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsInvalidTestApplicationBuilderErrorMessage">
        <source>Retry failed tests only works with builders of type 'Microsoft.Testing.Platform.Builder.TestApplicationBuilder'</source>
        <target state="translated">Reintentar pruebas con errores solo funciona con generadores de tipo "Microsoft.Testing.Platform.Builder.TestApplicationBuilder"</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsMaxPercentageOptionDescription">
        <source>Disable retry mechanism if the percentage of failed tests is greater than the specified value</source>
        <target state="translated">Deshabilitar el mecanismo de reintento si el porcentaje de pruebas con errores es mayor que el valor especificado</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsMaxTestsOptionDescription">
        <source>Disable retry mechanism if the number of failed tests is greater than the specified value</source>
        <target state="translated">Deshabilitar el mecanismo de reintento si el número de pruebas con errores es mayor que el valor especificado</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsNotSupportedInHotReloadErrorMessage">
        <source>Retry failed tests feature is not supported in hot reload mode</source>
        <target state="translated">La característica Reintentar pruebas con errores no se admite en el modo de recarga activa</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsNotSupportedInServerModeErrorMessage">
        <source>Retry failed tests feature is not supported in server mode</source>
        <target state="translated">La característica reintentar pruebas con errores no se admite en el modo de servidor</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsOptionDescription">
        <source>Enable retry failed tests</source>
        <target state="translated">Habilitar pruebas con errores de reintento</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsOptionIsMissingErrorMessage">
        <source>Option '{0}' requires option '{1}' to be specified</source>
        <target state="translated">La opción '{0}' requiere que se especifique la opción '{1}'</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsOptionSingleIntegerArgumentErrorMessage">
        <source>Option '{0}' expects a single integer argument</source>
        <target state="translated">La opción '{0}' espera un único argumento entero</target>
        <note />
      </trans-unit>
      <trans-unit id="RetryFailedTestsPercentageAndCountCannotBeMixedErrorMessage">
        <source>Options '{0}' and '{1}' cannot be used together</source>
        <target state="translated">Las opciones '{0}' y '{1}' no se pueden usar juntas</target>
        <note />
      </trans-unit>
      <trans-unit id="TestHostProcessExitedBeforeRetryCouldConnect">
        <source>Test host process exited before the retry service could connect to it. Exit code: {0}</source>
        <target state="translated">El proceso de host de prueba se cerró antes de que el servicio de reintento pudiera conectarse a él. Código de salida: {0}</target>
        <note />
      </trans-unit>
      <trans-unit id="TestSuiteCompletedSuccessfully">
        <source>
=====================
Tests suite completed successfully in {0} attempts
=====================</source>
        <target state="translated">
=====================
El conjunto de pruebas se completó correctamente en {0} intentos
=====================</target>
        <note />
      </trans-unit>
      <trans-unit id="TestSuiteFailed">
        <source>
=====================
Tests suite failed, total failed tests: {0}, exit code: {1}, attempt: {2}/{3}
=====================
</source>
        <target state="translated">
=====================
Error del conjunto de pruebas, total de pruebas erróneas: {0}, código de salida: {1}, intento: {2}/{3}
=====================
</target>
        <note />
      </trans-unit>
      <trans-unit id="TestSuiteFailedInAllAttempts">
        <source>
=====================
Tests suite failed in all {0} attempts
=====================</source>
        <target state="translated">
=====================
Error del conjunto de pruebas en los {0} intentos
=====================</target>
        <note />
      </trans-unit>
      <trans-unit id="TestSuiteFailedWithWrongExitCode">
        <source>Test suite failed with and exit code different that 2 (failed tests). Failure related to an unexpected condition. Exit code '{0}'</source>
        <target state="translated">Error del conjunto de pruebas con código de salida distinto de 2 (pruebas con errores). Error relacionado con una condición inesperada. '{0}' de código de salida</target>
        <note />
      </trans-unit>
    </body>
  </file>
</xliff>